; MobileEZChatCategoryPointers indexes (see mobile/fixed_words.asm)
	const_def
	const EZCHAT_POKEMON
	const EZCHAT_TYPES
	const EZCHAT_GREETINGS
	const EZCHAT_PEOPLE
	const EZCHAT_BATTLE
	const EZCHAT_EXCLAMATIONS
	const EZCHAT_CONVERSATION
	const EZCHAT_FEELINGS
	const EZCHAT_CONDITIONS
	const EZCHAT_LIFE
	const EZCHAT_HOBBIES
	const EZCHAT_ACTIONS
	const EZCHAT_TIME
	const EZCHAT_FAREWELLS
	const EZCHAT_THISANDTHAT

NUM_KANA EQU 45 ; length of SortedPokemon table (see mobile/fixed_words.asm)

MOBILE_LOGIN_PASSWORD_LENGTH EQU 17
EASY_CHAT_MESSAGE_WORD_COUNT EQU 6
EASY_CHAT_MESSAGE_LENGTH EQU EASY_CHAT_MESSAGE_WORD_COUNT * 2 ; every word uses 2 bytes
PHONE_NUMBER_LENGTH EQU 8
NUM_CARD_FOLDER_ENTRIES EQU 40
CARD_FOLDER_ENTRY_LENGTH EQU 41

if DEF(_CRYSTAL_AU)
ZIPCODE_LENGTH EQU 4
NUM_REGION_CODES EQU 25
REGION_CODE_STRING_LENGTH EQU 7
elif DEF(_CRYSTAL_EU)
ZIPCODE_LENGTH EQU 7
NUM_REGION_CODES EQU 40
REGION_CODE_STRING_LENGTH EQU 6
else ; US
ZIPCODE_LENGTH EQU 6
NUM_REGION_CODES EQU 64
REGION_CODE_STRING_LENGTH EQU 6
endc

ZIPCODE_FRAME_RIGHT_MARGIN EQU 1
