name: Build and Package ROM

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the develop branch
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}  
    strategy:
      matrix:       
        include:
          - os: ubuntu-20.04
            name: Linux-x64
    steps:

      # ==== Build Steps ====
      - name: Check out Source
        uses: actions/checkout@v3
        with:
          node-version: 16
          path: pokecrystal-mobile-en
          submodules: false

      # ==== Install/Get dependences ====
      - name: Linux Dependences
        if: matrix.name == 'Linux-x64'
        run: |
          # Install necessary tools
          sudo apt-get install -y bison pkg-config libpng-dev g++
          # Pull in RGBDS-0.6.1
          cd pokecrystal-mobile-en
          curl -Lo rgbds-0.6.1.tar.gz https://github.com/gbdev/rgbds/releases/download/v0.6.1/rgbds-0.6.1.tar.gz
          tar xvfz rgbds-0.6.1.tar.gz
          cd rgbds
          make
          cd ..

      # ==== Build ====
      - name: Build ROM
        if: (matrix.name == 'Linux-x64')
        shell: bash
        run: |
          cd pokecrystal-mobile-en
          make RGBDS=rgbds/
          cd ..
      # ==== Packaging ====
      - name: Store build
        if: (matrix.name == 'Linux-x64')
        uses: actions/upload-artifact@v3
        with:
          node-version: 16
          name: Pokecrystal_Build
          path: pokecrystal-mobile-en/pokecrystal.gbc
          # retention-days: 14
